TextTest will write diagnostics in /users/geoff/texttesttmp/texttestgeoff31Mar172418/TestSelf/CollateFiles/BadTargetPattern based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application GEN, version bad, checkout /nfs/vm/texttest/central_texttesttmp/texttestgeoff31Mar172418/TestSelf/CollateFiles/BadTargetPattern/TargetApp/./
Running GEN test-suite TargetApp
  Running GEN test-case Generate
WARNING : caught exception while running GEN test-case Generate changing state to UNRUNNABLE :
Comparing differences for GEN test-suite TargetApp
  GEN test-case Generate not compared:  exceptions.IOError: [Errno 21] Is a directory
