Description of exception thrown :
Traceback (most recent call last):
  File "/users/geoff/work/master/Testing/TextTest/lib/queuesystem.py", line 68, in notifyLifecycleChange
    self.sendData(fullData)
  File "/users/geoff/work/master/Testing/TextTest/lib/queuesystem.py", line 81, in sendData
    sendSocket.sendall(fullData)
  File "/carm/proj/texttest-tmp/geoff/texttest.03Mar134727.26045/texttest.sge/QueueSystems/ErrorHandling/SgeOnly/MasterResetsConnection/interceptor.py", line 11, in sendall
    raise socket.error, "Connection reset by peer"
error: Connection reset by peer
