TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.sgegeoff15Aug120656/QueueSystems/Console/ExternalErrors/SlaveCrashNoReport based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application SLEEP, version killing.badslavestart
Submitting SLEEP test-suite TargetApp to SGE queues
  Submitting SLEEP test-case Basic to default SGE queue
Unexpected output from qsub : Job 4810870 exited with exit code 0.
Terminating testing due to external interruption (RUNLIMIT2)
  Cancelling SLEEP test-case Basic in SGE (job 4810870)
  SLEEP test-case Basic not compared:
Slave exited
Description of exception thrown :
Traceback (most recent call last):
  File "/users/geoff/work/master/Testing/TextTest/testmodel.py", line 730, in getActionSequence
    actionSequenceFromConfig = self.target.getActionSequence()
  File "/users/geoff/work/master/Testing/TextTest/default.py", line 64, in getActionSequence
    return self._getActionSequence(makeDirs=1)
  File "/users/geoff/work/master/Testing/TextTest/default.py", line 127, in _getActionSequence
    actions = [ self.getTestProcessor() ]
  File "/users/geoff/work/master/Testing/TextTest/queuesystem.py", line 115, in getTestProcessor
    baseProcessor = default.Config.getTestProcessor(self)
  File "/users/geoff/work/master/Testing/TextTest/default.py", line 137, in getTestProcessor
    return [ self.getExecHostFinder(), SetUpTrafficHandlers(self.optionMap.has_key("rectraffic")), \
  File "/users/geoff/work/master/Testing/Automatic/texttest/error_config_modules/slaveerrstart.py", line 12, in getTestRunner
    wibble
NameError: global name 'wibble' is not defined
Error in set-up of application SLEEP - Exception thrown by 'slaveerrstart' configuration, while requesting 'action sequence'

At 12:08 creating batch report for application SLEEP ...file written
