Using Application HELLO
WARNING: Caught exception while running HELLO test-case Test changing state to UNRUNNABLE :
